backup:
  max-backups-per-area: 50

performance:
  max-area-size: 1000000
  rate-limit-cooldown: 1000

  # Restoration performance settings
  restore:
    # Batch sizes for restoration
    # Higher values = faster restoration but may cause lag
    # Lower values = slower restoration but less server impact
    max-batch-size: 400 # Maximum blocks per tick for large areas
    min-batch-size: 100 # Minimum blocks per tick for small areas
visualization:
  particle-distance: 50

selection:
  # Wooden hoe selection mode settings
  wooden-hoe:
    force-enabled: false # Can be enabled per-player via command
    auto-fallback: true # Automatically enable if WorldEdit fails or is unavailable
