# NPCItemPickup Configuration

# Enable or disable the plugin functionality
enabled: true

# Settings for item pickup behavior
pickup:
  # Radius in blocks for NPCs to detect items
  radius: 5.0

  # Delay in ticks between pickup attempts (20 ticks = 1 second)
  delay: 20

  # Maximum number of items an NPC can hold
  max_items: 256

  # Whether NPCs should move towards items when picking them up
  move_to_items: true

  # Speed multiplier when moving to items (1.0 = normal speed)
  movement_speed: 1.2

# Settings for item dropping on death
drop:
  # Whether items should be dropped when NPC dies
  enabled: true

  # Chance (0.0 to 1.0) that items will be dropped on death
  drop_chance: 1.0

  # Whether to drop items at exact NPC location or scatter them
  scatter_items: true

  # Radius for scattering items (if scatter_items is true)
  scatter_radius: 2.0

# Item filtering settings
item_filter:
  # Whether to use whitelist (true) or blacklist (false)
  use_whitelist: false

  # List of allowed items (if use_whitelist is true)
  whitelist:
    - "DIAMOND"
    - "GOLD_INGOT"
    - "IRON_INGOT"

  # List of blocked items (if use_whitelist is false)
  blacklist:
    - "BEDROCK"

# NPC specific settings
npc_settings:
  # List of NPC IDs that should NOT pick up items
  # Use /npcpickup disable <npc_id> command to add NPCs to this list
  disabled_pickup: []

# Thief mode settings - allows NPCs to take items from chests
thief_mode:
  # Enable thief mode functionality
  enabled: true

  # Radius in blocks for NPCs to detect chests (5x5x5 area)
  chest_radius: 5.0

  # Number of items to take per tick (higher values = faster stealing)
  items_per_tick: 1

  # List of NPC IDs that are in thief mode
  # Use /npcpickup thief <npc_id> command to add NPCs to this list
  thief_npcs: []

  # Delay in ticks between theft attempts (20 ticks = 1 second)
  theft_delay: 10

  # Whether thieves should move towards chests when stealing
  move_to_chests: true

  # Maximum distance for stealing from containers (blocks)
  theft_distance: 4.0

# Debug settings
debug:
  enabled: false
  log_pickups: true
  log_drops: true
  log_theft: true
