name: NPCItemPickup
version: ${project.version}
main: com.example.npcitempickup.NPCItemPickupPlugin
api-version: 1.20
depend: [Citizens]
author: YourName
description: ${project.description}

commands:
  npcpickup:
    description: NPC Item Pickup commands
    usage: /<command> [reload|toggle|status]
    permission: npcpickup.admin

permissions:
  npcpickup.admin:
    description: Allows access to NPC Item Pickup admin commands
    default: op
