database:
  type: "SQLite"
  sqlite:
    file: "achievements.db"
  mysql:
    host: "localhost"
    port: 3306
    database: "achievements"
    username: "root"
    password: ""

progress-bar:
  enabled: false
  type: "ACTIONBAR"
  boss-bar:
    color: "GREEN"
    style: "SOLID"
  update-interval: 20
  show-on-progress: false

notifications:
  sound:
    enabled: true
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0
  title:
    enabled: true
    fade-in: 10
    stay: 70
    fade-out: 20
  chat:
    enabled: true
    broadcast: false
  firework:
    enabled: true

sound:
  enabled: true
  notification-sound: "ENTITY_PLAYER_LEVELUP"
  volume: 1.0
  pitch: 1.0

firework:
  enabled: true

gui:
  rows: 6
  items-per-page: 45
  auto-refresh: true
  refresh-interval: 60

categories:
  - "Building"
  - "Combat"
  - "Mining"
  - "Crafting"
  - "Exploration"
  - "Farming"
  - "Other"

defaults:
  category: "Other"
  icon: "PAPER"
  points: 10